name: ci configuration
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: grab the code
        run: git clone https://github.com/100625-Newman/taskmaster-lesson.git
      - name: python install pip
        run: |
          sudo apt install python3-pip -y
      - name: install requirements
        run: |
          cd taskmaster-lesson/app
          ls -lha
          pip install -r requirements.txt
      - name: run tests
        run: |
          cd taskmaster-lesson/tests
          ls -lha
          
          pytest /home/runner/work/taskmaster-lesson/taskmaster-lesson/app/app.py

        