name: Terraform deployment

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform_deployment:
    name:  Terraform Plan (PR)
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v4
        with:
            terraform_version: "1.14.4"
  
      - name: download-artifact
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v19
        with:
          name: teraform-state
          path: terraform
          workflow: terraform_deployment.yml
      - name: terraform-init-plan
        run: |
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
          export AWS_REGION=us-east-1
          cd terraform
          terraform init
          terraform apply --auto-approve

      - name: upload-artifact
        continue-on-error: true
        uses: actions/upload-artifact@v7
        with:
          name: terraform-state
          path: terraform/terraform.tfstate
          