name: Terraform Automation

on:
  push:
    branches: [main]

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Hello World!"

      - name: First step
        run: |
          ls -al
          echo '###############################'
          pwd
          echo '###############################'
      - name: Check code
        uses: actions/checkout@v4.3.1
        
      - name: Third step
        run: |
          ls -al
          echo '###############################'
          pwd
          echo '###############################'

