name: Terraform Deployment

on:
  push:
    branches: [main]
    # paths: ['terraform/**']

jobs:
  terraform_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v4.3.1
        
      - name: debug-step
        continue-on-error: true
        run: |
          terraform --version      

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.4"

      - name: debug-step-2
        run: |
          terraform --version

      - name: download-artifact
        uses: dawidd6/action-download-artifact@v19
        with:
          name: terraform-state
          path: terraform


      - name: terraform-apply
        run: |
          cd terraform
          terraform apply --auto-approve
          
      - name: upload-artifact
        uses: actions/upload-artifact@v7
        with: 
          name: terraform-state
          path: terraform/terraform.tfstate

          




