name: Terraform Deployment
on:
  push:
    branches: [ main ]
jobs:
  build_runner:
    runs-on: ubuntu-latest
    steps:
       - name : echo "Hello World"
         run: echo "Hello World" > hello.txt
       - name: check file existence
         run: cat hello.txt && ls -lha 