name: Terraform Deployment
on:
  push:
    branches: [ main ]
jobs:
  build_runner:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v5
       - name : grab the code
         run: git clone https://github.com/100625-Newman/taskmaster-lesson.git
       - name: check file existence
         run: ls -lha
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v4
         with:
           terraform_version: 1.14.7

       - name: Check terraform existence
         run: |
              echo "##################################"
              which terraform && terraform --version
              echo "##################################"
       - name: Check aws existence
         run: |
              echo "##################################"     
              which aws && aws --version
              echo "##################################"
       - name: Install AWS CLI
         run: |
              echo "installing aws cli"
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install --update
              rm awscliv2.zip
              echo "cleaned up aws cli installer"
       - name: set aws credentials + tf init plan
         run: |
           echo "setting up aws credentials"
           export AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
           export AWS_SECRET_ACCESS=${{ secrets.AWS_SECRET_ACCESS }}
           export AWS_DEFAULT_REGION=us-east-1
           echo "###################################"
           pwd
           echo "##################################"
           cd taskmaster-lesson     
           ls -lha
           cd terraform
           terraform init
           terraform plan