name: tf_pr

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build_runner:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
       - name: Checkout code
         uses: actions/checkout@v5
       - name : grab the code
         run: git clone https://github.com/100625-Newman/taskmaster-lesson.git
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v4
         with:
           terraform_version: 1.14.7
       - name: download-artifacts
         uses: /dawidd6/action-download-artifact@v19
         with:
           name: tf state documentation
           continue-on-error: true
           path: terraform/
           workflow: tf_deployment.yaml
       - name: set aws credentials + tf init plan apply
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
           aws-region: us-east-1
       - name: tf plan
         run: |
           cd taskmaster-lesson/terraform
           terraform init

       - name: terraform plan
         uses: dflook/terraform-plan@v2
         with:
           path: taskmaster-lesson/terraform